import type { CharacterData } from "./types"

export const defaultCharacter: CharacterData = {
  name: "",
  class: "",
  race: "",
  level: "1",
  background: "",
  stats: {
    strength: 10,
    dexterity: 10,
    constitution: 10,
    intelligence: 10,
    wisdom: 10,
    charisma: 10,
  },
  combatStats: {
    armorClass: 10,
    currentHp: 0,
    maxHp: 0,
  },
  savingThrows: {
    strength: false,
    dexterity: false,
    constitution: false,
    intelligence: false,
    wisdom: false,
    charisma: false,
  },
  spellSlots: {
    cantrips: { known: 0 },
    level1: { total: 0, used: [], known: 0 },
    level2: { total: 0, used: [], known: 0 },
    level3: { total: 0, used: [], known: 0 },
    level4: { total: 0, used: [], known: 0 },
    level5: { total: 0, used: [], known: 0 },
    level6: { total: 0, used: [], known: 0 },
    level7: { total: 0, used: [], known: 0 },
    level8: { total: 0, used: [], known: 0 },
    level9: { total: 0, used: [], known: 0 },
  },
  inventory: [],
  equipment: [],
  proficiencies: [],
  skills: [
    { name: "Acrobatics", ability: "dexterity", proficient: false, expertise: false },
    { name: "Animal Handling", ability: "wisdom", proficient: false, expertise: false },
    { name: "Arcana", ability: "intelligence", proficient: false, expertise: false },
    { name: "Athletics", ability: "strength", proficient: false, expertise: false },
    { name: "Deception", ability: "charisma", proficient: false, expertise: false },
    { name: "History", ability: "intelligence", proficient: false, expertise: false },
    { name: "Insight", ability: "wisdom", proficient: false, expertise: false },
    { name: "Intimidation", ability: "charisma", proficient: false, expertise: false },
    { name: "Investigation", ability: "intelligence", proficient: false, expertise: false },
    { name: "Medicine", ability: "wisdom", proficient: false, expertise: false },
    { name: "Nature", ability: "intelligence", proficient: false, expertise: false },
    { name: "Perception", ability: "wisdom", proficient: false, expertise: false },
    { name: "Performance", ability: "charisma", proficient: false, expertise: false },
    { name: "Persuasion", ability: "charisma", proficient: false, expertise: false },
    { name: "Religion", ability: "intelligence", proficient: false, expertise: false },
    { name: "Sleight of Hand", ability: "dexterity", proficient: false, expertise: false },
    { name: "Stealth", ability: "dexterity", proficient: false, expertise: false },
    { name: "Survival", ability: "wisdom", proficient: false, expertise: false },
  ],
  traits: [],
  feats: [],
  spells: [],
}
